# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.sln'

- task: CmdLine@2
  inputs:
    script: |
      echo  '$(System.DefaultWorkingDirectory)'
      dir
      cd $(System.DefaultWorkingDirectory)\Web\IdentityServer\
      dotnet publish -c Release -o C:\temp\publish\release\identityserver
      cd ..\..\
      cd $(System.DefaultWorkingDirectory)\Web\ChamadosApi\
      dotnet publish -c Release -o C:\temp\publish\release\chamadosapi

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'C:\temp\publish\release\identityserver'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/identity_$(Build.BuildId).zip'
    replaceExistingArchive: true